---
project_name: peggo

env:
  - CGO_ENABLED=1

before:
  hooks:
    - go mod download

builds:
  - main: ./
    id: "peggo"
    binary: peggo
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X github.com/umee-network/peggo/cmd/peggo.Version={{ .Version }} -X github.com/umee-network/peggo/cmd/peggo.Commit=$(COMMIT)={{ .Commit }}
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - README.md
      - LICENSE

release:
  github:
    owner: umee-network
    name: peggo
  name_template: "v{{.Version}}"

checksum:
  name_template: SHA256SUMS-v{{.Version}}.txt
  algorithm: sha256

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

changelog:
  skip: false
