#install packages for build layer
FROM ubuntu:xenial as builder
# COPY --from=solcbuilder $SOLC_LOCATION /usr/local/bin/solc 

RUN apt-get update && apt-get install git gcc make perl jq libc-dev curl wget build-essential -y
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash
RUN apt-get install nodejs -y

# Install ganache-cli globally
# ENV NODE_VERSION 16.13.0
# RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash \
#     && export NVM_DIR="$HOME/.nvm" \
#     && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  \
#     && [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" \
#     && nvm install $NODE_VERSION \
#     && nvm alias default $NODE_VERSION \
#     && nvm use default

# ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
# ENV PATH      $NVM_DIR/v$NODE_VERSION/bin:$PATH
RUN npm install -g ganache-cli

RUN wget https://binaries.soliditylang.org/linux-amd64/solc-linux-amd64-v0.8.2+commit.661d1103
RUN mv solc-linux-amd64-v0.8.2+commit.661d1103 solc && chmod +x solc && mv solc /usr/local/bin/solc
RUN solc --version

RUN wget -P /tmp https://golang.org/dl/go1.17.2.linux-amd64.tar.gz

RUN tar -C /usr/local -xzf /tmp/go1.17.2.linux-amd64.tar.gz
RUN rm /tmp/go1.17.2.linux-amd64.tar.gz

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"

# Download deps
WORKDIR /src
COPY . .

# Install umee
RUN cd .. && git clone --depth 1 --branch v0.4.0-rc1 https://github.com/umee-network/umee.git
RUN cd umee && make install & cd /src/



RUN go mod download
CMD CHAIN_ID=umee-local STAKE_DENOM=uumee DENOM=uumee CLEANUP=1 ./test/cosmos/multinode.sh umeed && ganache-cli -h "0.0.0.0" -p 8545 -m "concert load couple harbor equip island argue ramp clarify fence smart topic" -l 999999999999999 & PEGGO_TEST_EVM_RPC="http://0.0.0.0:8545" go test ./...